all:
  hosts:
  children:
    collectd:
      hosts:
        127.0.0.1:
      vars:
        ansible_connection: local
        telegraf_server: '"localhost"'
        telegraf_server_port: '"25826"'
        vm_id: 'vm_id_'
        tenant_id: 'tenant_id_'
        disk_type_map: {'.*sda.*': 'ssd', '.*sdb.*': 'sata', '.*': 'hdd'}

