all:
  hosts:
  children:
    collectd:
      vars:
          telegraf_server: '"172.16.112.51"'
          telegraf_port: '"25826"'
      hosts:
        172.16.112.52:
          ansible_user: debian
          vm_id: 'vm_id_1'
          tenant_id: 'tenant_id_0'
          disk_type_instance: '{"vda": "disk1"}' 
          disk_type_map: '{".*vda.*": "ssd"}'
        172.16.112.55:
          ansible_user: debian
          vm_id: 'vm_id_2'
          tenant_id: 'tenant_id_0'
          disk_type_instance: '{"vda": "disk1"}' 
          disk_type_map: '{".*vda.*": "ssd"}'
        185.62.103.127:
          ansible_user: root
          vm_id: 'vm_id_3'
          tenant_id: 'tenant_id_0'
          disk_type_instance: '{"vda": "disk1"}' 
          disk_type_map: '{".*vda.*": "ssd"}'
